### ISSUE TITLE
crash on launch 

### ISSUE THREAD

**Issue by gjcbo** [manofit/swift_project#2]
GJTabbarController.swift 

奔溃
  self.addChildController(ChildController: MainViewController(), Title: "首页", DefaultImage: UIImage(named:"")!, SelectedImage: UIImage(named:"")!)
crash信息：“Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value”

**Comment by manofit** [comment]
因为没有图片资源，所以报错，版权问题，正在考虑使用占位符。
